version: '3.8'
services:
  nest-service:
    build: ./services/nest-service
    ports:
      - 3000:3000
    depends_on:
      - go-service
  go-service:
    build: ./services/go-service
    ports:
      - 3001:3001
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.85.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - 4317:4317
